"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";

type CartItem = { id: string; name: string; code: string; price: number; quantity: number };
export default function CartPage() {
  const [items, setItems] = useState<CartItem[]>([]);
  useEffect(() => { setItems(JSON.parse(localStorage.getItem("plantcare-cart") ?? "[]")); }, []);
  function save(next: CartItem[]) { setItems(next); localStorage.setItem("plantcare-cart", JSON.stringify(next)); window.dispatchEvent(new Event("plantcare-cart")); }
  const total = useMemo(() => items.reduce((sum,item) => sum + item.price * item.quantity, 0), [items]);
  return <main className="min-h-screen bg-[#fbfdf8] px-5 py-12 text-emerald-950"><div className="mx-auto max-w-4xl"><Link href="/" className="font-serif text-2xl font-bold">❧ PlantCare</Link><div className="mt-10 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-emerald-700">Your selection</p><h1 className="mt-2 font-serif text-5xl">Shopping cart</h1></div><Link href="/products" className="text-sm font-bold underline">Continue shopping</Link></div>{items.length === 0 ? <div className="mt-10 rounded-3xl border border-dashed border-emerald-950/20 bg-white p-14 text-center"><p className="font-serif text-3xl">Your cart is empty</p><Link href="/products" className="mt-5 inline-block rounded-full bg-emerald-900 px-6 py-3 text-sm font-bold text-white">Browse plants</Link></div> : <div className="mt-10 grid gap-6 lg:grid-cols-[1fr_300px]"><div className="space-y-3">{items.map(item => <article key={item.id} className="flex items-center gap-4 rounded-3xl border border-emerald-950/10 bg-white p-4"><div className="grid size-20 place-items-center rounded-2xl bg-emerald-100 text-4xl">♣</div><div className="min-w-0 flex-1"><h2 className="font-bold">{item.name}</h2><p className="text-xs text-emerald-950/50">{item.code}</p><strong className="mt-2 block">₹{item.price}</strong></div><div className="flex items-center gap-2"><button aria-label={`Reduce ${item.name}`} onClick={() => save(item.quantity === 1 ? items.filter(x => x.id !== item.id) : items.map(x => x.id === item.id ? {...x,quantity:x.quantity-1}:x))} className="grid size-8 place-items-center rounded-full border">−</button><span>{item.quantity}</span><button aria-label={`Increase ${item.name}`} onClick={() => save(items.map(x => x.id === item.id ? {...x,quantity:x.quantity+1}:x))} className="grid size-8 place-items-center rounded-full border">+</button></div></article>)}</div><aside className="h-fit rounded-3xl bg-emerald-950 p-6 text-white"><h2 className="font-serif text-2xl">Order summary</h2><div className="mt-6 flex justify-between text-sm text-white/70"><span>Subtotal</span><span>₹{total}</span></div><div className="mt-3 flex justify-between text-sm text-white/70"><span>Delivery</span><span>Calculated later</span></div><div className="mt-6 flex justify-between border-t border-white/15 pt-5 text-xl font-bold"><span>Total</span><span>₹{total}</span></div><Link href="/login" className="mt-6 block rounded-full bg-lime-300 px-5 py-3 text-center text-sm font-bold text-emerald-950">Sign in to checkout</Link></aside></div>}</div></main>;
}
