import { products } from "./products";
const databaseImage=(category:string,index=0)=>products.filter(product=>product.category===category)[index]?.image??products[0].image;
export type BlogPost={slug:string;title:string;excerpt:string;category:string;readTime:string;date:string;image:string;intro:string;sections:{heading:string;body:string}[]};
export const blogPosts:BlogPost[]=[
{slug:"how-to-water-indoor-plants",title:"How to Water Indoor Plants Without Overwatering",excerpt:"A simple routine for checking soil, watering deeply and keeping roots healthy.",category:"Indoor plants",readTime:"5 min read",date:"2026-08-20",image:databaseImage("crotons",4),intro:"More houseplants struggle from too much water than from one missed watering. Learn to read the plant and soil instead of following a rigid calendar.",sections:[{heading:"Check before you pour",body:"Push a finger 2–3 cm into the potting mix. Water most common indoor plants only when that top layer feels dry. Lift the pot too: a light pot usually needs water."},{heading:"Water the whole root zone",body:"Pour slowly until a little water drains from the bottom, then empty the saucer. A small daily splash leaves dry pockets and encourages shallow roots."},{heading:"Adjust for the season",body:"Plants use water faster during bright, warm growth and more slowly in cool or cloudy weather. Check regularly, but let the plant decide the timing."}]},
{slug:"best-low-maintenance-plants-for-beginners",title:"7 Low-Maintenance Plants for New Plant Parents",excerpt:"Beginner-friendly choices that tolerate normal homes and busy schedules.",category:"Beginner guides",readTime:"6 min read",date:"2026-08-18",image:databaseImage("crotons",0),intro:"A good first plant should suit your light, available space and care routine. These forgiving choices make learning enjoyable.",sections:[{heading:"Start with resilient varieties",body:"Aloe vera, lucky bamboo, crotons and hardy herbs are practical starting points. Choose a healthy plant with firm stems and clean leaves."},{heading:"Match the light",body:"Bright indirect light suits many houseplants. Keep foliage away from harsh afternoon sun unless the variety is sun-loving."},{heading:"Build one easy habit",body:"Choose a weekly day to inspect soil, leaves and pests. Inspection—not automatic watering—is the habit that prevents most problems."}]},
{slug:"balcony-gardening-india",title:"Balcony Gardening in India: A Practical Starter Plan",excerpt:"Plan sunlight, containers and crops for a productive small-space garden.",category:"Small spaces",readTime:"7 min read",date:"2026-08-15",image:databaseImage("planters",0),intro:"Even a compact balcony can grow herbs, flowers and seasonal vegetables when containers are matched to light and drainage.",sections:[{heading:"Map your sunlight",body:"Observe the balcony for one full day. Fruiting vegetables generally need the brightest position; leafy herbs and many ornamentals tolerate gentler light."},{heading:"Choose containers with drainage",body:"Every planter needs drainage holes. Use a loose potting mix and leave room below the rim so watering does not wash soil away."},{heading:"Grow upward",body:"Use rail planters, shelves and trellises while keeping heavy pots on stable floor areas. Leave airflow between plants to reduce fungal problems."}]},
{slug:"monsoon-plant-care-tips",title:"Monsoon Plant Care: 8 Ways to Prevent Root Rot",excerpt:"Protect container plants during long wet spells and humid weather.",category:"Seasonal care",readTime:"5 min read",date:"2026-08-12",image:databaseImage("plant-care",2),intro:"Rain revives gardens, but constantly wet roots and low airflow can quickly cause trouble. A few preventive steps make monsoon care easier.",sections:[{heading:"Pause routine watering",body:"Check the potting mix after rain and water only when needed. Move sensitive pots under cover during continuous downpours."},{heading:"Keep drainage clear",body:"Raise pots slightly so holes can drain freely. Remove blocked debris and never let containers stand in collected water."},{heading:"Inspect leaves",body:"Remove damaged foliage, space plants for airflow and check leaf undersides for pests. Act early before a small issue spreads."}]},
{slug:"organic-pest-control-home-garden",title:"Organic Pest Control for a Healthier Home Garden",excerpt:"Identify common pests early and use a calm, targeted response.",category:"Plant health",readTime:"6 min read",date:"2026-08-09",image:databaseImage("plant-care",0),intro:"Pest control works best when you identify the problem, isolate the plant and start with the least disruptive treatment.",sections:[{heading:"Inspect and isolate",body:"Check new plants before placing them with your collection. If you see webbing, sticky residue or clusters of insects, isolate the plant while treating it."},{heading:"Start mechanically",body:"A firm stream of water can remove many aphids and mites. Wipe broad leaves and prune heavily affected growth with clean tools."},{heading:"Use treatments carefully",body:"If needed, apply a product labelled for the pest and plant. Test a small area first, follow the label, and avoid spraying in hot direct sun."}]},
{slug:"start-a-kitchen-herb-garden",title:"How to Start a Kitchen Herb Garden",excerpt:"Grow useful herbs near your kitchen with the right light and harvest routine.",category:"Edible gardening",readTime:"5 min read",date:"2026-08-05",image:databaseImage("herbs",1),intro:"Fresh herbs are rewarding in small spaces because regular harvesting encourages new growth and brings the garden into everyday cooking.",sections:[{heading:"Pick herbs you use",body:"Begin with two or three favourites rather than many varieties. Mint, coriander and other locally suitable herbs are useful choices when their light needs are met."},{heading:"Give roots room",body:"Use containers with drainage and avoid crowding several vigorous herbs into one small pot. Mint is often easiest in its own container."},{heading:"Harvest correctly",body:"Take small amounts regularly, cutting just above a healthy leaf node. Avoid removing more than one-third of a plant at once."}]}
];
export const getPost=(slug:string)=>blogPosts.find(post=>post.slug===slug);
