"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";

export default function RegisterPage() {
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const data = new FormData(event.currentTarget); if (data.get("password") !== data.get("confirmPassword")) { setMessage("Passwords do not match."); setBusy(false); return; } const response = await fetch("/api/register", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(data)) }); const result = await response.json() as { error?: string }; if (!response.ok) { setMessage(result.error ?? "Registration failed."); setBusy(false); return; } window.location.href = "/login"; }
  return <main className="grid min-h-screen place-items-center bg-[radial-gradient(circle_at_top_right,#dceecb,transparent_35%),#fbfdf8] px-5 py-12"><div className="w-full max-w-lg rounded-[2rem] border border-emerald-950/10 bg-white p-8 shadow-2xl shadow-emerald-950/10"><Link href="/" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-emerald-800 text-white">❧</span><b className="font-serif text-2xl">PlantCare</b></Link><h1 className="mt-8 font-serif text-4xl">Create your account</h1><p className="mt-2 text-sm text-emerald-950/60">Save your cart, addresses, and order history.</p><form onSubmit={submit} className="mt-7 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">First name<input name="firstName" required className="mt-2 w-full rounded-2xl border border-emerald-950/15 px-4 py-3 font-normal"/></label><label className="text-sm font-bold">Last name<input name="lastName" required className="mt-2 w-full rounded-2xl border border-emerald-950/15 px-4 py-3 font-normal"/></label><label className="text-sm font-bold sm:col-span-2">Email<input name="email" type="email" required className="mt-2 w-full rounded-2xl border border-emerald-950/15 px-4 py-3 font-normal"/></label><label className="text-sm font-bold">Password<input name="password" type="password" minLength={8} required className="mt-2 w-full rounded-2xl border border-emerald-950/15 px-4 py-3 font-normal"/></label><label className="text-sm font-bold">Confirm password<input name="confirmPassword" type="password" minLength={8} required className="mt-2 w-full rounded-2xl border border-emerald-950/15 px-4 py-3 font-normal"/></label>{message && <p role="alert" className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900 sm:col-span-2">{message}</p>}<button disabled={busy} className="rounded-full bg-emerald-900 px-5 py-3.5 font-bold text-white disabled:opacity-50 sm:col-span-2">{busy ? "Creating account..." : "Create account"}</button></form><p className="mt-6 text-center text-sm text-emerald-950/60">Already registered? <Link href="/login" className="font-bold text-emerald-800 underline">Sign in</Link></p></div></main>;
}
